spring:
  application:
    name: demo-data-grid-spring
  profiles:
    active: @spring.profiles.active@
server:
  http2:
    enabled: true
  port: 8082
app:
  cache:
    delete: true
infinispan:
  remote:
    server-list: 127.0.0.1:11222
    client-intelligence: BASIC
    auth-username: admin
    auth-password: admin