quarkus:
  log:
    level: INFO
  http:
    port: 8081
  infinispan-client:
    hosts: localhost:11222
    username: admin
    password: admin
    client-intelligence: BASIC
    cache:
      demo-data-grid:
        configuration-resource: demoDataGridCache.xml
"%prod":
  quarkus:
    http:
      port: 8080
    infinispan-client:
      client-intelligence: HASH_DISTRIBUTION_AWARE
      hosts: ${INFINISPAN_HOSTS}
      username: ${INFINISPAN_USER}
      password: ${INFINISPAN_PASSWD}